# Generated by Django 2.2 on 2019-06-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190612_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='languages',
            field=models.ManyToManyField(to='main_app.Language'),
        ),
    ]
